# Generated by Django 4.1.5 on 2023-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_urun'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='fiyat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
