# Generated by Django 4.1.5 on 2023-04-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_alter_urun_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='isim',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.kategori'),
        ),
    ]
