# Generated by Django 4.1.5 on 2023-04-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_sepet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='fiyat',
            field=models.IntegerField(),
        ),
    ]
