# Generated by Django 4.1.5 on 2023-04-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_alter_urun_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='toplamFiyat',
            field=models.IntegerField(),
        ),
    ]
