# Generated by Django 4.1.5 on 2023-04-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_odeme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Odeme',
        ),
    ]
